
[versions]
#compose-compiler = "1.5.15"
compose-plugin = "1.7.1"
agp = "8.7.2"
junitJupiterApi = "5.11.3"
kotlin = "2.0.21"
kotlin-ksp = "2.0.21-1.0.26"
kotlin-coroutine = "1.9.0"
kotlin-datetime = "0.6.1"
compose = "1.7.5"
compose-activity = "1.9.3"
shimmer = "1.3.1"
coil = "2.7.0"
coil3 = "3.0.4"
room = "2.7.0-alpha11"
sqlite = "2.5.0-SNAPSHOT"
media3 = "1.5.0"
ktor = "3.0.1"
brotli = "0.1.2"
palette = "1.0.0"
desugaring = "2.1.3"
appcompat = "1.7.0"
#core = "1.0.1"
#core-ktx = "1.13.1" # NO UPDATE TO 1.15 DROP THEME IN RES\STYLES ANDROID 11+
media = "1.7.0"
material = "1.7.5"
materialdesktop = "1.7.1"
material3 = "1.4.0-alpha04"
androidmaterial = "1.12.0"
constraintlayout = "1.1.0"
translator = "1.1.1"
kotlin-csv = "1.9.3"
monetcompat = "0.4.1"
navigation = "2.8.4"
timber = "5.0.1"
crypto = "1.1.0-alpha06"
loggingInterceptor = "4.12.0"
math3 = "3.6.1"
toasty = "1.5.2"
haze = "1.1.1"
androidyoutubeplayer = "12.1.1"
glance = "1.1.1"
kizzyrpc = "1.0.71"
gson = "2.11.0"
mediaPlayerKMP = "2.0.4"
navigationKMP = "2.7.0-alpha07" # Do NOT update to "2.8.0-dev1920", it breaks scrolling text
vlcj = "4.8.3"
kotlinxCoroutinesSwing = "1.9.0"
hilt = "2.51.1"

[libraries]
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterApi" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterApi" }
kotlin-coroutines = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutine"}
kotlin-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version = "kotlin-coroutine" }
kotlin-datetime = {group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlin-datetime"}
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-ui = {group = "androidx.compose.ui", name = "ui", version.ref = "compose"}
compose-ui-util = {group = "androidx.compose.ui", name = "ui-util", version.ref = "compose"}
compose-ui-graphics-android = {group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "compose"}
compose-ripple = {group = "androidx.compose.material", name = "material-ripple", version.ref = "compose"}
compose-shimmer = {group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "shimmer"}
compose-activity = {group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity"}
compose-animation = {group = "androidx.compose.animation", name = "animation", version.ref = "compose"}
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose"}
compose-coil = {group = "io.coil-kt", name = "coil-compose", version.ref = "coil"}
room = {group = "androidx.room", name = "room-ktx", version.ref = "room"}
room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "room"}
room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "room"}
room-sqlite-bundled = { module= "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
media3-exoplayer = {group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3"}
media3-session = {group = "androidx.media3", name = "media3-session", version.ref = "media3"}
media3-datasource-okhttp = {group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "media3"}
ktor-client-core = {group = "io.ktor", name = "ktor-client-core", version.ref = "ktor"}
ktor-client-okhttp = {group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor"}
ktor-client-content-negotiation = {group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor"}
ktor-client-encoding = {group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor"}
ktor-client-serialization = {group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor"}
ktor-serialization-json = {group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor"}
brotli = {group = "org.brotli", name = "dec", version.ref = "brotli"}
palette = {group = "androidx.palette", name = "palette", version.ref = "palette"}
desugaring = {group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugaring"}
appcompat = {group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat"}
appcompat-resources = {group = "androidx.appcompat", name = "appcompat-resources", version.ref = "appcompat"}
#core-splashscreen = {group = "androidx.core", name = "core-splashscreen", version.ref = "core"}
#core-ktx = {group = "androidx.core", name = "core-ktx", version.ref = "core-ktx"}
media = {group = "androidx.media", name = "media", version.ref = "media"}
material = {group = "androidx.compose.material", name = "material", version.ref = "material"}
material-icon-desktop = {group = "org.jetbrains.compose.material", name = "material-icons-extended-desktop", version.ref = "materialdesktop"}
material3 = {group = "androidx.compose.material3", name = "material3-android", version.ref = "material3"}
androidmaterial = {group = "com.google.android.material", name = "material", version.ref = "androidmaterial"}
constraintlayout = {group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout"}
translator = { group = "com.github.therealbush", name = "translator", version.ref = "translator"}
kotlin-csv = { group = "com.github.doyaaaaaken", name = "kotlin-csv-jvm", version.ref = "kotlin-csv"}
monetcompat = { group = "com.github.KieronQuinn", name = "MonetCompat", version.ref = "monetcompat"}
navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation"}
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber"}
crypto = { group = "androidx.security", name = "security-crypto", version.ref = "crypto"}
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
math3 = {group = "org.apache.commons", name = "commons-math3", version.ref = "math3"}
toasty = {group = "com.github.GrenderG", name = "Toasty", version.ref = "toasty"}
haze = {group = "dev.chrisbanes.haze", name = "haze", version.ref = "haze"}
androidyoutubeplayer = {group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "androidyoutubeplayer"}
glance-widgets = {group = "androidx.glance", name = "glance-appwidget", version.ref = "glance"}
kizzy-rpc = {group = "com.github.dead8309", name = "KizzyRPC", version.ref = "kizzyrpc"}
gson = {group = "com.google.code.gson", name = "gson", version.ref = "gson"}
mediaplayer-kmp = { group = "io.github.khubaibkhan4", name = "mediaplayer-kmp", version.ref = "mediaPlayerKMP" }
navigation-kmp = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigationKMP"}
vlcj = { group = "uk.co.caprica", name = "vlcj", version.ref = "vlcj"}
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil3" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutinesSwing" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
room = { id = "androidx.room", version.ref = "room" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }


