name: Build KBuild variant every week

on:
  schedule:
  # Gotta wait until contributors.json is updated
  - cron: '0 0 * * 0'  # Every Sunday at 0AM

  # Allow manual trigger
  workflow_dispatch:

  # Run jobs when this workflow is updated
  push:
    branches: [kbuild]
    paths:
      - .github/workflows/weekly-kbuild-build.yml

# Prevent multiple jobs from running at the same time
concurrency:
  group: 'weekly-deploy'
  cancel-in-progress: false  # Don't cancel any in-progress runs in this group

jobs:
  setup:
    runs-on: ubuntu-latest
    # Set date as a variable
    outputs:
      BUILD_DATE: ${{ steps.date.outputs.date }}

    steps:
    - name: Get date
      id: date
      # Output of "October 2 2024" will be "20241002"
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

  build-full-variant:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.1

    - name: Setup Java 21
      uses: actions/setup-java@v4.4.0
      with:
        java-version: "21"
        distribution: "corretto"
        cache: gradle

    - name: Build with Gradle
      run: ./gradlew assembleFull

    - name: Upload built artifact for next job
      uses: actions/upload-artifact@v4.4.1
      with:
        name: unsigned-full-apk
        path: composeApp/build/outputs/apk/full/RiMusic-kbuild-full-unsigned.apk

  build-minified-variant:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Setup Java 21
        uses: actions/setup-java@v4.4.0
        with:
          java-version: "21"
          distribution: "corretto"
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew assembleMinified

      - name: Upload built artifact for next job
        uses: actions/upload-artifact@v4.4.1
        with:
          name: unsigned-minified-apk
          path: composeApp/build/outputs/apk/minified/RiMusic-kbuild-minified-unsigned.apk

  sign-apk:
    needs: [build-full-variant, build-minified-variant]
    runs-on: ubuntu-latest

    steps:
    - name: A place to store APKS
      run: mkdir unsigned

    - name: Retrieve APK
      uses: actions/download-artifact@v4.1.8
      with:
        path: unsigned

    - name: Sign APK
      uses: Tlaster/android-sign@v1.2.2
      with:
        releaseDirectory: |
          unsigned/unsigned-minified-apk
          unsigned/unsigned-full-apk

        signingKeyBase64: "${{ secrets.KEYSTORE_IN_BASE64 }}"
        keyStorePassword: "${{ secrets.KEYSTORE_PASSWD }}"
        alias: "${{ secrets.KEY_ALIAS }}"
        keyPassword: "${{ secrets.KEY_PASSWD }}"

        output: build/kbuild/signed

      env:
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: Remove trails
      run: |
        for filename in build/kbuild/signed/*.apk; do mv "$filename" "${filename//-signed}"; done
        
        for filename in build/kbuild/signed/*.apk; do mv "$filename" "${filename//-unsigned}"; done

    - name: Upload signed APK(s) for next job
      uses: actions/upload-artifact@v4.4.1
      with:
        name: signed-apks
        path: build/kbuild/signed/RiMusic-*.apk

  upload-to-release:
    needs: [sign-apk, setup]
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve APK
      uses: actions/download-artifact@v4.1.8
      with:
        name: signed-apks

    - name: Upload built APK to release
      uses: softprops/action-gh-release@v2
      with:
        files: RiMusic-*.apk
        name: RiMusic Weekly Build | KBuild | ${{ needs.setup.outputs.BUILD_DATE }}
        tag_name: "weekly-kbuild"
        body: |
          <div align="center">
            <img src="https://raw.githubusercontent.com/knighthat/RiMusic/refs/heads/kbuild/assets/design/latest/app_logo.svg" width="300" height="100" />
            <p><b>RiMusic</b> KBuild</p>
            <p>Custom build by @knighthat</p>
          </div>

          ## ❗ WARNING ❗
          
          This build is not an official release, it is just ideas before it's pushed into [upstream branch](https://github.com/fast4x/RiMusic).\
          If you are interested, head down to the download section and get a copy.
          
          ## 📲 Installation
          
          This version is signed by me. Android treats this build as if this is a different app, thus,
          your old RiMusic app will not be removed
          
          ## Verification
          
          > Always check for signature before installing any app you downloaded from Github or any other APK distributor.
          
          ### My signature hashes
          
          | Hash algorithm |  Variant  |  Digest  |
          |---|---|---|
          | SHA-256 | kbuild  | 8c1bf1d9f63288f36837aba5ba3dbef929d0e78055d3cd6d9ec8d26ae487f56e |
          | SHA-1 | kbuild  | 2dae81c56e516193f433c04b5b8b2f79c39ecec2 |
          | MD5 | kbuild  | b8ac8c9d91e7c6972d966e0e167e0e71 |
          
          ## FAQ
          
          <details> 
          <summary>Q1: How do I download your build?</summary>
            <blockquote>
              Right below this article, there are link(s) to prebuilt APK(s).<br>
              Select the one that fits your need to start the download.
            </blockquote>
          </details>
          <details>
          <summary>Q2: How verify build's signature?</summary>
            <blockquote>
              There are 2 main methods:
              <ol>
                <li>
                  Built-in <a href="https://stackoverflow.com/questions/7104624/how-do-i-verify-that-an-android-apk-is-signed-with-a-release-certificate" target="_blank" rel="noopener noreferrer">jarsigner</a>
                </li>
                <li>
                  <a href="https://developer.android.com/tools/apksigner#options-verify" target="_blank" rel="noopener noreferrer">apksigner</a> from AndroidSDK
                </li>
              </ol>
            </blockquote>
          </details>
          <details>
          <summary>Q3: What's the difference between <quote>full</quote> and <quote>minified</quote>?</summary>
            <blockquote>
              The difference lies in their sizes.<br>
              "minified" version has its unused code/resources removed before compiling.<br>
              But it isn't perfect, some users experience instability on minified version, so I also
              include "full" version to help those to continue using the app
            </blockquote>
          </details>

        token: ${{ secrets.RELEASE_TOKEN }}
        generate_release_notes: true
